stages:
  - build

build_project:
  stage: build
  image: python:3.9-slim  # Используем стандартный для этого курса образ
  script:
    - echo "Передаем файлы DAG"
  artifacts:
    paths:
      - dags/
